#!/usr/bin/env Rscript

library(plumber)
# 'endpoints.R' is the location of the endpoints file
tryCatch(
  # Specifying expression
  expr = {
    pr("endpoints.R") %>%
      pr_run(host = "0.0.0.0", port = 8080)
  },
  # Specifying error message
  error = function(e) {
    write(e %>% as.character(), file = "/opt/ml_vol/outputs/errors/serve_failure.txt", append =
            FALSE)
  }
)
